### ISSUE TITLE
run_scan.py wrong path

### ISSUE THREAD

**Issue by ihotep** [ICTU/openvas-docker#3]
Running the second command causes following error:

`root@test:/tmp# docker run --rm -v $(pwd):/openvas/results/:rw ictu/openvas-docker ./run_scan.py 192.168.1.11 openvas_scan.html
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./run_scan.py\": stat ./run_scan.py: no such file or directory": unknown.
`
Caused by wrong path for run_scan.py (above command tries to run it from "/" instead of /openvas/.

Fix:

docker run --rm -v $(pwd):/openvas/results/:rw ictu/openvas-docker **/openvas**/run_scan.py 192.168.1.11 openvas_scan.html

**Comment by fniessink** [comment]
What is "the second command" referring to?

**Comment by fniessink** [comment]
We found your problem, it was only present on the develop branch. We have merged the develop branch to the master, made some other changes, and are building a new Docker image right now. See https://cloud.docker.com/u/ictu/repository/docker/ictu/openvas-docker.
