### ISSUE TITLE
Scan Script 

### ISSUE THREAD

**Issue by MBravestarr** [ICTU/openvas-docker#8]
Which type of scan config is happening during the scan (full and fast, full and fast ultimate, etc...) and which port lists are being scanned? Thank you

**Comment by ds-o** [comment]
Hi @MBravestarr, the config used is "Full and Fast", it is hardcoded:

https://github.com/ICTU/openvas-docker/blob/153b73d4fa5f630c4ed23a4b93c44e7b3ba769c9/run_scan.py#L11

https://github.com/ICTU/openvas-docker/blob/153b73d4fa5f630c4ed23a4b93c44e7b3ba769c9/run_scan.py#L35

For the ports, the "OpenVAS default" port list is used, please see: https://docs.greenbone.net/GSM-Manual/gos-4/en/performance.html

Please let me know if this helps you.

**Comment by MBravestarr** [comment]
This is great, thank you. One more question. Is there a way to have it conduct an authenticated scan?

**Comment by ds-o** [comment]
At this moment unfortunately not. But i'm planning to build support for this.

**Comment by ds-o** [comment]
Duplicate of #9 closing
