### ISSUE TITLE
Implement authenticated scan

### ISSUE THREAD

**Issue by enwelder** [ICTU/openvas-docker#9]
We would like to see the possibility of an authenticated scan added. What we need most is authentication through SSH, preferably with ssh key. 

Thank you very much!

**Comment by ds-o** [comment]
Will add authentication using SSH

**Comment by ds-o** [comment]
@enrico2828 authentication using SSH password or key is now added!

https://github.com/ICTU/openvas-docker/commit/153b73d4fa5f630c4ed23a4b93c44e7b3ba769c9

Please pull the latest version from Docker Hub.
